import Head from 'next/head'
import Link from 'next/link'
//import styles from '../styles/Home.module.css'
import Header from '../components/Header/Header'
import Login from '../components/Login'
import { useSession, signIn, signOut, getSession } from 'next-auth/react'
import SignIn from '../components/Authentication/SignIn'

import Sidebar from '../components/SideView/Sidebar'
import Feeds from '../components/mainFeed/Feeds'
import Widgets from '../components/SideView/Widgets'
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore'
import { db } from '../firebase'
//import { getSession } from 'next-auth/react'

export default function Home() {
  const { data: session, status } = useSession()

  const { loading, authenticated, unauthenticated } = status
  let homePage = ''
  if (!session) {
    homePage = <SignIn />
  } else {
    homePage = (
      <>
        <Header />
        <main className='flex'>
          {' '}
          <Sidebar />
          <Feeds />
          <Widgets/>
        </main>{' '}
      </>
    )
  }
  return (
    <div className='h-screen overflow-hidden bg-gray-100'>
      <Head>
        <title> FACEBOOK CLONE APP </title>{' '}
        <meta
          name='cloning facebook with nextjs'
          content='Generated by create next app'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>{' '}
      {homePage}{' '}
    </div>
  )
}



// export  const  getServerSideProps =  async(context)=>{
//   const session = getSession(context)
//   const posts = onSnapshot( query(collection(db, 'posts'), orderBy('timestamp', 'desc')),(snapshot)=>{
//       snapshot?.docs.map((doc) => {
//           return {
//             id: doc.id,
//             ...doc.data(),
//             timestamp:null
//           }
//         })

//   })


// return{
//   props:{
//     session,

//     posts

//   }
// }

// }
